import type { IconType } from 'react-icons';
import {
  RiAddLine,
  RiAlertLine,
  RiArrowDropDownLine,
  RiArrowRightLine,
  RiArrowUpDownLine,
  RiArrowUpLine,
  RiBold,
  RiCalendarLine,
  RiChat1Line,
  RiCheckboxBlankLine,
  RiCheckboxFill,
  RiCheckLine,
  RiCircleLine,
  RiCloseLine,
  RiCloudOffLine,
  RiDeleteBinLine,
  RiErrorWarningLine,
  RiExternalLinkLine,
  RiEyeLine,
  RiEyeOffLine,
  RiGithubFill,
  RiGoogleFill,
  RiHome2Line,
  RiImage2Line,
  RiInformation2Line,
  RiItalic,
  RiLoader2Line,
  RiLoader4Line,
  RiLoader5Line,
  RiLogoutBoxRLine,
  RiLoopRightLine,
  RiMedicineBottleLine,
  RiMenLine,
  RiMentalHealthLine,
  RiPagesLine,
  RiPencilLine,
  RiRadioButtonLine,
  RiSaveLine,
  RiSearch2Line,
  RiSendPlaneLine,
  RiSortAsc,
  RiSortDesc,
  RiStarFill,
  RiStarHalfLine,
  RiStarLine,
  RiSubtractLine,
  RiSurveyLine,
  RiUpload2Line,
  RiUserHeartLine,
  RiWomenLine,
} from 'react-icons/ri';
import { FaShopify } from 'react-icons/fa';

// Custom Arxiv SVG Icon
const ArxivIcon = ({ className }: { className?: string }) => (
  <svg
    viewBox="0 0 24 24"
    fill="currentColor"
    className={className}
    xmlns="http://www.w3.org/2000/svg"
  >
    <path d="M12 2L3 7v10l9 5 9-5V7l-9-5zm0 2.18l6.09 3.39L12 11.18 5.91 7.57 12 4.18zM5 9.37l6 3.34v6.11l-6-3.34V9.37zm8 9.45v-6.11l6-3.34v6.11l-6 3.34z"/>
  </svg>
);

export type FaIconType = IconType;

export const FaIcon = {
  Arxiv: ArxivIcon,
  Shopify: FaShopify,
  Alert: RiAlertLine,
  ArrowDropDown: RiArrowDropDownLine,
  ArrowRight: RiArrowRightLine,
  ArrowUp: RiArrowUpLine,
  Bold: RiBold,
  Calendar: RiCalendarLine,
  Circle: RiCircleLine,
  CircleFill: RiRadioButtonLine,
  Chat: RiChat1Line,
  Check: RiCheckLine,
  CheckboxEmpty: RiCheckboxBlankLine,
  CheckboxFill: RiCheckboxFill,
  Close: RiCloseLine,
  CloudOff: RiCloudOffLine,
  Consultation: RiMedicineBottleLine,
  Edit: RiPencilLine,
  Empty: RiCircleLine,
  Error: RiErrorWarningLine,
  ExternalLink: RiExternalLinkLine,
  Female: RiWomenLine,
  FileUpload: RiUpload2Line,
  FlashAlert: RiAlertLine,
  FlashInfo: RiInformation2Line,
  FlashSuccess: RiCheckLine,
  FlashWarning: RiErrorWarningLine,
  Form: RiPagesLine,
  Github: RiGithubFill,
  Google: RiGoogleFill,
  Home: RiHome2Line,
  Image: RiImage2Line,
  Info: RiInformation2Line,
  Italic: RiItalic,
  LoaderCircle: RiLoader4Line,
  LoaderCog: RiLoader2Line,
  LoaderSpinner: RiLoader5Line,
  LoaderSync: RiLoopRightLine,
  Male: RiMenLine,
  Mother: RiUserHeartLine,
  PasswordHide: RiEyeOffLine,
  PasswordShow: RiEyeLine,
  Patients: RiMentalHealthLine,
  Plus: RiAddLine,
  Save: RiSaveLine,
  Search: RiSearch2Line,
  Send: RiSendPlaneLine,
  SignOut: RiLogoutBoxRLine,
  SortAsc: RiSortAsc,
  SortDesc: RiSortDesc,
  SortUpDown: RiArrowUpDownLine,
  Star: RiStarLine,
  StarFull: RiStarFill,
  StarHalf: RiStarHalfLine,
  StepperMinus: RiSubtractLine,
  StepperPlus: RiAddLine,
  Survey: RiSurveyLine,
  Trash: RiDeleteBinLine,
};
