/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OkRouteImport } from './routes/ok'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PdfPaperIdRouteImport } from './routes/pdf.$paperId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OkRoute = OkRouteImport.update({
  id: '/ok',
  path: '/ok',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfPaperIdRoute = PdfPaperIdRouteImport.update({
  id: '/pdf/$paperId',
  path: '/pdf/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ok': typeof OkRoute
  '/register': typeof RegisterRoute
  '/pdf/$paperId': typeof PdfPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ok': typeof OkRoute
  '/register': typeof RegisterRoute
  '/pdf/$paperId': typeof PdfPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ok': typeof OkRoute
  '/register': typeof RegisterRoute
  '/pdf/$paperId': typeof PdfPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ok' | '/register' | '/pdf/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ok' | '/register' | '/pdf/$paperId'
  id: '__root__' | '/' | '/ok' | '/register' | '/pdf/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OkRoute: typeof OkRoute
  RegisterRoute: typeof RegisterRoute
  PdfPaperIdRoute: typeof PdfPaperIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ok': {
      id: '/ok'
      path: '/ok'
      fullPath: '/ok'
      preLoaderRoute: typeof OkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$paperId': {
      id: '/pdf/$paperId'
      path: '/pdf/$paperId'
      fullPath: '/pdf/$paperId'
      preLoaderRoute: typeof PdfPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OkRoute: OkRoute,
  RegisterRoute: RegisterRoute,
  PdfPaperIdRoute: PdfPaperIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
